name: IslandArchitect
author: ClouriaNetworkDevelopers
authors: [Endermanbugzjfc, "callumrawlinson - helped with Github Templates and random ore"]
api: 3.0.0
version: 1.2.1
main: Clouria\IslandArchitect\IslandArchitect
website: https://github.com/crnw-dev/IslandArchitect
depend: [SkyBlock]
softdepend: [InvCrashFix]
load: POSTWORLD

permissions:
  island-architect:
    default: op
    children:
      island-architect.cmd:
        description: Permission to use the "/island-architect" command
      island-architect.convert:
        description: Permission to convert a island into JSON island template file
        children:
          island.architect.convert.*:
            description: Allow a user to checkout and modify specified islands