name: IslandArchitect
author: ClouriaNetworkDevelopers
authors: [Endermanbugzjfc]
authors: [callumrawlinson - helped with Github Templates and random ore]
api: 3.0.0
version: 1.0.2
main: Clouria\IslandArchitect\IslandArchitect
website: https://github.com/crnw-dev/IslandArchitect
depend: [SkyBlock, InvCrashFix]

permissions:
  island-architect:
    default: op
    children:
      island-architect.cmd: []
      island-architect.convert:
        description: Permission to convert a island into JSON island template file
      island-architect.reset-all:
        description: Permission to destruct anyone's convert session for saving for saving up server resource
